### ISSUE TITLE
Fix deployment of Operator

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/open-liberty-operator#1]
I originally created the operator by going through [these instructions](https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md) and everything worked fine.  I was able to deploy CRs (YAML files, such as [this one](https://github.com/OpenLiberty/open-liberty-operator/blob/master/deploy/demo.yaml)) without any errors.

However, as I started to put these artifacts into a format that is suitable for OperatorHub.io something went wrong.  It could have been during the merge of the service account, role and role-binding into a single YAML file, or it could have been when I renamed the API group that the CRD belongs to.  

This workitem will go through the deployment of the operator + CRD + demo_CR and debug which parts have gone wrong.  The successful end result is that our demo_CR should install the app we're pointing to. At the moment it does not.

**Comment by arthurdm** [comment]
I noticed that in OpenShift I had to bind the `admin` role to the `open-liberty-operator` Service Account to get things working - which definitely sounds like an issue with the generated Role.

**Comment by kaczyns** [comment]
I think this is fixed based on the contents of #2 #3 #4 and #5.  We still need to work out a better way to automate creating the security context constraint and authorizing it, but that can be done manually for now.
