### ISSUE TITLE
Revisit maturity model of the operator

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/open-liberty-operator#102]
With day-2 operations and recent enhancements to this Operator we should revisit the maturity level we claim.  See [here](https://operatorhub.io/getting-started) for an illustration of the levels.

**Comment by arthurdm** [comment]
I suggest that in 0.4.0 we update the maturity level to `Auto Pilot`, updating the main doc page to call out the fact we have things like: horizontal auto-scaling (including scaling to 0 with knative / serverless), automatic metrics / logging integration,  dynamic service binding (both app->app and app->resources),  automatic certificate manager integration, and social login client configuration injection.

**Comment by leochr** [comment]
OL operator is now at `Auto Pilot` level: https://operatorhub.io/operator/open-liberty
