### ISSUE TITLE
Update documentation to differentiate between Vanilla Kubernetes and OKD/OCP

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty-operator#131]
### Is your feature request related to a generic (non-Open Liberty) problem?

Not exactly. This request is to have the documentation updated once vanilla Kubernetes has been enabled under https://github.com/application-stacks/runtime-component-operator/issues/56

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Documentation clearly describe how to use the Operator in vanilla Kubernetes and OKD/OpenShift.

**Comment by arturdzm** [comment]
#do
