### ISSUE TITLE
Route TLS termination Reencrypt with CA ClusterIssuer: failed to access Open Liberty home page

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty-operator#134]
### What did you do?
Attempting to access Open Liberty application through Open Liberty Operator CR instance (OLA) and Route TLS termination reencrypt but the application page failed to display and the message `Application is not available` is displayed instead.

@leochr please note in the initial scenario when the problem was encountered, the sso spec was enabled in OLA, but since the problem is already seen without using sso spec, I've trimmed the below deployment yaml by removing sso spec and therefore no `acme-olapp-sso` secret is required to recreate the problem.

Steps to recreate:
1. Install Open Liberty Operator
- kubectl apply -f https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/daily/openliberty-app-crd.yaml
- curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/daily/openliberty-app-operator.yaml \
  | sed -e "s/OPEN_LIBERTY_WATCH_NAMESPACE/acme-test/" \
  | kubectl apply -n acme-test -f -
 where acme-test is the namespace

2. Set up Open Shift Cert-manager with CA ClusterIssuer
- install cert-manager (reference: https://cert-manager.io/docs/installation/openshift/)
   - oc create namespace cert-manager
   - oc apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.14.1/cert-manager.yaml
- create CA secret: oc apply -f ca-secret.yaml
(rename to remove .txt)
[ca-secret.yaml.txt](https://github.com/OpenLiberty/open-liberty-operator/files/4472109/ca-secret.yaml.txt)

- deploy CA ClusterIssuer: oc apply -f ca-clusterissuer.yaml
(rename to remove .txt)
[ca-clusterissuer.yaml.txt](https://github.com/OpenLiberty/open-liberty-operator/files/4472110/ca-clusterissuer.yaml.txt)

- Verify:
```
# oc get clusterissuers company-ca  -o wide
NAME         READY   STATUS                AGE
company-ca   True    Signing CA verified   19h
```
```
# oc get all -n cert-manager
NAME                                           READY   STATUS    RESTARTS   AGE
pod/cert-manager-579d48dff8-9kh4q              1/1     Running   0          18h
pod/cert-manager-cainjector-789955d9b7-w82lh   1/1     Running   2          14d
pod/cert-manager-webhook-64869c4997-jrcxl      1/1     Running   0          14d

NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/cert-manager           ClusterIP   172.30.215.15   <none>        9402/TCP   14d
service/cert-manager-webhook   ClusterIP   172.30.60.221   <none>        443/TCP    14d

NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cert-manager              1/1     1            1           14d
deployment.apps/cert-manager-cainjector   1/1     1            1           14d
deployment.apps/cert-manager-webhook      1/1     1            1           14d

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/cert-manager-579d48dff8              1         1         1       14d
replicaset.apps/cert-manager-cainjector-789955d9b7   1         1         1       14d
replicaset.apps/cert-manager-webhook-64869c4997      1         1         1       14d
```
pod/cert-manager-579d48dff8-9kh4q  log:
[cert-manager-pod.log](https://github.com/OpenLiberty/open-liberty-operator/files/4472111/cert-manager-pod.log)

3. Set up test application:
- Dockerfile
(rename to remove .txt)
[Dockerfile.txt](https://github.com/OpenLiberty/open-liberty-operator/files/4472112/Dockerfile.txt)

- server.xml
(rename to remove .txt)
[server.xml.txt](https://github.com/OpenLiberty/open-liberty-operator/files/4472113/server.xml.txt)

- test EAR 
(unzip to get the ear file)
[AcmeWebClientEar.ear.zip](https://github.com/OpenLiberty/open-liberty-operator/files/4472114/AcmeWebClientEar.ear.zip)

- Note: Below docker build is for OCP image registry, some information in the command may need to be customized to match to the expected env, e.g, Fyre host, namespace.
- docker build -t default-route-openshift-image-registry.apps.offal.os.fyre.ibm.com/acme-test/acme .
- docker push default-route-openshift-image-registry.apps.offal.os.fyre.ibm.com/acme-test/acme

4. Deploy application:
- oc apply -f acme-olapp.yaml
- Note: the attached yam is based on the same Fyre host and name space as referred above.
(rename to remove .txt)
[acme-olapp.yaml.txt](https://github.com/OpenLiberty/open-liberty-operator/files/4472118/acme-olapp.yaml.txt)

- pod log:

[messages.log](https://github.com/OpenLiberty/open-liberty-operator/files/4472157/messages.log)
- Note: from OCP console, when checking the pod log, we see the following 2 lines at the top:
```
Found mounted TLS certificates, generating keystore
Found mounted TLS CA certificate, adding to truststore
```
- Verify, when comparing acme-route-tls ca.crt:
```
-----BEGIN CERTIFICATE-----
MIIC+TCCAeGgAwIBAgIJAKPGwKDl/5HnMA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
BAMMCGpvc2h2YW5sMB4XDTE5MDgyMjE2MDU1OFoXDTI5MDgxOTE2MDU1OFowEzER
MA8GA1UEAwwIam9zaHZhbmwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQCwhSB/qW6/kLb2zpu+EJvD9wHFaq+QA/0JH/Lllyo7zAFx+HHq+COAbk+C8B4t
/HUEsns5RL09CZ+X4j6pbJFdKduPxXu5ZVYnkxYpUDU7yg7OSKSZzTnIZ723sMs0
R6jYn/Drj4xXMJEfHUDqYeSWlZr3qi1EFa0c7fVDxH+4xtZtNNFOjH7c6D/vWkIg
WQUxiwusse6KMOWjDnv/4Vrjel2QgUYUbHCyeZHmcti+K0LWCfo/Rg6PulwrbDkh
jmOgYt30pdhX0OZkAuklfUDHfp8bjbCoI2taYABA6AKjKsO35LAEU79CL1mLVHuZ
ACI5Ujija3VPWVHSwmJPJyuxAgMBAAGjUDBOMB0GA1UdDgQWBBQml5dTAZixFKhj
93wucRWhao/tQjAfBgNVHSMEGDAWgBQml5dTAZixFKhj93wucRWhao/tQjAMBgNV
HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQB+klkRNJUKBLX8yYkyuU2RHcBv
GhmmDjJIsOJHZsoYXdLlG1pZNFjjPaOL8vh44Vl98RhEZBHsLT1KMbp1su6Cqj0r
UG1kpRBef+IOMT4MU7vRICi7UOlRLp1Wp0F8la3hPOcRb2yOfFqXXyZWXf4t0B45
tHi+ZCNHB9FxjSRycbGYVk+TKpvhJaSYNMGJ3dxDKaP7+Dx3XcK6sAnIAkhyI8aj
NU+mw8/tmRkP4In/kXAR+Ri0qUmHj/vwvnk4Km7ZUy1FYH8DMeS5Nksn+/uHlRxR
V7Dnn039TRmgKbAqN72gKNLo5cZ+y/YqDAYHYrn98SQT9JDgtI/K/ATpW8dX
-----END CERTIFICATE-----
```
and acme-svc-tls ca.crt or route's destinationCACertificat:
```
-----BEGIN CERTIFICATE-----
MIIC+TCCAeGgAwIBAgIJAKPGwKDl/5HnMA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
BAMMCGpvc2h2YW5sMB4XDTE5MDgyMjE2MDU1OFoXDTI5MDgxOTE2MDU1OFowEzER
MA8GA1UEAwwIam9zaHZhbmwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQCwhSB/qW6/kLb2zpu+EJvD9wHFaq+QA/0JH/Lllyo7zAFx+HHq+COAbk+C8B4t
/HUEsns5RL09CZ+X4j6pbJFdKduPxXu5ZVYnkxYpUDU7yg7OSKSZzTnIZ723sMs0
R6jYn/Drj4xXMJEfHUDqYeSWlZr3qi1EFa0c7fVDxH+4xtZtNNFOjH7c6D/vWkIg
WQUxiwusse6KMOWjDnv/4Vrjel2QgUYUbHCyeZHmcti+K0LWCfo/Rg6PulwrbDkh
jmOgYt30pdhX0OZkAuklfUDHfp8bjbCoI2taYABA6AKjKsO35LAEU79CL1mLVHuZ
ACI5Ujija3VPWVHSwmJPJyuxAgMBAAGjUDBOMB0GA1UdDgQWBBQml5dTAZixFKhj
93wucRWhao/tQjAfBgNVHSMEGDAWgBQml5dTAZixFKhj93wucRWhao/tQjAMBgNV
HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQB+klkRNJUKBLX8yYkyuU2RHcBv
GhmmDjJIsOJHZsoYXdLlG1pZNFjjPaOL8vh44Vl98RhEZBHsLT1KMbp1su6Cqj0r
UG1kpRBef+IOMT4MU7vRICi7UOlRLp1Wp0F8la3hPOcRb2yOfFqXXyZWXf4t0B45
tHi+ZCNHB9FxjSRycbGYVk+TKpvhJaSYNMGJ3dxDKaP7+Dx3XcK6sAnIAkhyI8aj
NU+mw8/tmRkP4In/kXAR+Ri0qUmHj/vwvnk4Km7ZUy1FYH8DMeS5Nksn+/uHlRxR
V7Dnn039TRmgKbAqN72gKNLo5cZ+y/YqDAYHYrn98SQT9JDgtI/K/ATpW8dX
-----END CERTIFICATE-----

```
5. Access Open Liberty home page:
- Access routes URL e.g.,  https://acme-acme-test-env.apps.floes.os.fyre.ibm.com
- The error will be displayed.

### What did you expect to see?

A clear and concise description of what you expected to happen (or insert a code snippet). If possible, add `OpenLibertyApplication` CR.

Open Liberty page:

![image](https://user-images.githubusercontent.com/27024803/79164079-e992a880-7da5-11ea-99c5-a5a37a28f617.png)

### What did you see instead?

A clear and concise description of what you expected to happen (or insert a code snippet).

![image](https://user-images.githubusercontent.com/27024803/79162930-b3ecc000-7da3-11ea-90e2-66d2fbe799d3.png)

### Environment

* Kubernetes version information:

* OpenShift version information (if applicable):

```
# oc version
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```

* Appsody CLI version (if applicable):

* Appsody Stack (if applicable):

**Comment by meiaus** [comment]
@brutif @chunlongliang-ibm - fyi

**Comment by arturdzm** [comment]
[4/13/20 21:25:33:241 UTC] 0000002a com.ibm.ws.ssl.config.WSKeyStore                             E CWPKI0033E: The keystore located at /opt/ol/wlp/output/defaultServer/resources/security/key.p12 did not load because of the following error: keystore password was incorrect

This is due to the keystore being replaced by the new one at runtime. But server.xml has custom password.

Please remove:

<keyStore password="{xor}EzY9Oi0rJg==" id="defaultKeyStore"/>

**Comment by meiaus** [comment]
Thanks @arthurdm for catching it.  I've thought the custom password would be replaced.  I'll double check on `SEC_TLS_TRUSTDEFAULTCERTS` overrides on 
```
 truststore.xml
<server description="Default Server">
    <ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" trustDefaultCerts="${SEC_TLS_TRUSTDEFAULTCERTS}" />
    <keyStore id="defaultTrustStore" location="${server.output.dir}/resources/security/trust.p12" type="PKCS12" password="+XtxnNpuY6e2Cz5KALZh17YZ2Dcj2T9TKWoO22gFC5c=" />
    <variable name="SEC_TLS_TRUSTDEFAULTCERTS" defaultValue="false"/>
</server>
```
Rebuilt the image and the deployment got the expected keystore.
```
[4/15/20 4:43:48:312 UTC] 0000002a com.ibm.ws.ssl.config.WSKeyStore                             I Successfully loaded default keystore: /opt/ol/wlp/output/defaultServer/resources/security/key.p12 of type: PKCS12
```

**Comment by meiaus** [comment]
Closing ...
