### ISSUE TITLE
Update logo for operator hub

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty-operator#151]
Not really a bug, but the other categories didn't really fit....

The logo on operator hub is not great because of it's size and aspect ratio.  This issue is to replace the log with one that should work better, which is this - https://github.com/OpenLiberty/logos/blob/master/logomark/png/square/OL_logomark_square_392.png

**Comment by leochr** [comment]
@gcharters @arthurdm Here is how the new logo would render:

<img width="685" alt="new_logo" src="https://user-images.githubusercontent.com/18424008/81308755-2d4c9b00-9050-11ea-82df-686da2a7f25b.png">

**Comment by leochr** [comment]
Current rendering for comparision:
<img width="707" alt="current" src="https://user-images.githubusercontent.com/18424008/81308822-405f6b00-9050-11ea-86ca-a928c73fe166.png">

**Comment by gcharters** [comment]
@leochr  That looks much better. Thanks!

**Comment by arthurdm** [comment]
thx @leochr - looks good!

**Comment by leochr** [comment]
Updated OperatorHub page for OL with new logo: https://operatorhub.io/operator/open-liberty
