### ISSUE TITLE
Update for sso provider "oauth2" in https://github.com/OpenLiberty/ci.docker/blob/master/SECURITY.md

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty-operator#159]
Not sure if the following SECURITY.md page is handled via "open-liberyt-operator" repo, but since the following docker build problem is experienced from running with Open Liberty Operator, tracking this ticket here:

https://github.com/OpenLiberty/ci.docker/blob/master/SECURITY.md

Recently when running docker build with Dockerfile which was tested in April, e.g.
```
FROM openliberty/open-liberty:full-java8-openj9-ubi

# Optional functionality
ARG TLS=true
ARG SEC_SSO_PROVIDERS="oauth oidc facebook google github twitter linkedin"
#ARG OPENJ9_SCC=false
ARG VERBOSE=true

COPY --chown=1001:0  server.xml /config/
COPY --chown=1001:0  AcmeWebClientEar.ear /config/apps

# This script will add the requested XML snippets and gow image to be fit-for-purpose
RUN configure.sh

```
the following failure appeared:
```
++ grep oauth
+ [[ -n sso-oauth2.xml ]]
+ cp /opt/ol/helpers/build/configuration_snippets/sso-oauth.xml /config/configDropins/defaults
cp: cannot stat '/opt/ol/helpers/build/configuration_snippets/sso-oauth.xml': No such file or directory
```

After consulting with @brutif and @leochr, it's realized, the sso provider "oauth" has been changed to "oauth2".  
After updating Dockerfile to reflect the new provider "oauth2", 
```
ARG SEC_SSO_PROVIDERS="oauth2 oidc facebook google github twitter linkedin"
```
the problem is the resolved.

Please update the readme accoringly:
https://github.com/OpenLiberty/ci.docker/blob/master/SECURITY.md

![image](https://user-images.githubusercontent.com/27024803/82160585-08300780-985c-11ea-8a09-d395f8caed23.png)

**Comment by leochr** [comment]
Issue moved to [OpenLiberty/ci.docker #185](https://github.com/OpenLiberty/ci.docker/issues/185) via [**ZenHub**](https://www.zenhub.com/)
