### ISSUE TITLE
Update x-descriptors for application CRD CSV and add them fro trace and dump CRDs

### ISSUE THREAD

**Issue by arturdzm** [OpenLiberty/open-liberty-operator#172]
Update x-descriptors for better integration with OpenShift OLM UI

**Comment by leochr** [comment]
More info on Cluster Service Version (CSV). It also has information on X-Descriptors : https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md

Example x-descriptors (in OpenLibertyApplication): https://github.com/OpenLiberty/open-liberty-operator/blob/7b53b217ce10dd61b27a1fc752384d16f5129146/deploy/olm-catalog/open-liberty-operator-certified/open-liberty-operator.v0.6.0.clusterserviceversion.yaml#L197

Testing the operator locally: https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md#manual-testing-on-kubernetes

**Comment by leochr** [comment]
It'll be good if the pod to gather the trace/dump on can be selected from a list. For dump, it'll be good to have a checkbox for the `include` options (thread, heap, system).
