### ISSUE TITLE
Grafana support thanos prometheus datasource

### ISSUE THREAD

**Issue by NissesSenap** [OpenLiberty/open-liberty-operator#190]
### Is your feature request related to a generic (non-Open Liberty) problem?

No

### Is your feature request related to a problem?

Using https://github.com/OpenLiberty/open-liberty-operator/blob/master/deploy/dashboards/metrics/RHOCP4.3-GrafanaOperator3.0.2-Grafana5.2/open-liberty-grafana-mpMetrics2.x.yml I'm unable to get any graphs.

I think this is due to  the query adds the prometheus server where he the data comes from which dosen't match due to that I'm grabbing my data through Thanos so it the name of the prometheus in the query dosen't match with the prometheus datasourceName.

My datasourceName=Promethus which is Thanos in OCP 4.3 and above if you are using that as a middle layer.
And the real proemtheus that performs the query is called: openshift-user-wokrload-monitroing/user-workload.
And that is what gets forwarded to grafana.

So in the current query you ask for pod="my-pod-name", prometheus="openshift-user-workload-monitoring/user-workload"

Bellow you can see the query that gets created.
<img width="902" alt="query_open-orig" src="https://user-images.githubusercontent.com/14774899/87831396-af90e100-c883-11ea-8105-f044698c1089.PNG">

Here you can see how i remove they prometheus query and add the pod name manually and I'm able to find the data.

<img width="931" alt="query_working" src="https://user-images.githubusercontent.com/14774899/87831426-c0d9ed80-c883-11ea-9217-1000d4e67406.PNG">

FYI this is a tech preview feature in OCP 4.2 and forward if I remember correctly but I think anyone that uses Thanos would get this issue.

### Describe the solution you'd like

I think the easiest solution would be to just remove the prometheus part of the query and just rely on the datasource that you are using.

I guess this could create issues if you have some big instance of clusters and in theory the operator could generate the same pod-names for 2 clusters and this could create issues. My guess is that it would show up as duplicates in the grafana UI.
I haven't run super big clusters at the same time so I don't know the chance of that happening relatively at the same time. 

For more background see: https://github.com/OpenLiberty/open-liberty/issues/13010

**Comment by Yushan-Lin** [comment]
Hi @NissesSenap, I'm trying to setup the environment, and not too familiar with Thanos. Do you have info about what you did to set it up Thanos?

**Comment by NissesSenap** [comment]
Hey I'm on vacation but I write some instructions on how to reproduce in OCP/okd 4 next week.
Might be possible with CRC, don't know if they have disable some features.

If you need pure kubernetes instructions it will probably take me some more time since I haven't tried it my self.

**Comment by Yushan-Lin** [comment]
Hi @NissesSenap, would you still like us to look into this?

**Comment by NissesSenap** [comment]
Hi @Yushan-Lin , sorry for the very long delay.
I forgot to update the issue during my vacation and first week back I had to focus on other things.

Here comes the rather long explanation on how to recreate my env. If you get any issues to reproduce it just ping me. We can also do a zoom/slack call or something to work on it together. 

# Install Grafana on OCP 4

So this isn't super straight forward and sadly it will take kind of allot of understanding to be able to recreate
the same env I got...

## OCP env

You have two options when setting up your own OCP 4 environment.

You can use crc or you can use a none laptop cluster.
If you have access to a "normal" OCP 4 cluster I would suggest using that.

### CRC

If you are going to use crc to run OCP 4 you will have to follow the instructions here:
https://code-ready.github.io/crc/#starting-monitoring-alerting-telemetry_gsg

I don't have a strong enough laptop to be able to verify this. But I assume it works :)

### Preperation Prometheus

To monitor your own services you need to perform the following:

https://docs.openshift.com/container-platform/4.5/monitoring/monitoring-your-own-services.html#enabling-monitoring-of-your-own-services_monitoring-your-own-services

Make sure that configmap cluster-monitoring-config in openshift-monitoring ns looks the following:

```oc -n openshift-monitoring edit configmap cluster-monitoring-config```

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    techPreviewUserWorkload:
      enabled: true
```

## Grafana

To make the installation of grafana together with the built in Thanos of OCP I created a small helm repo + grabbed the grafna operator yaml.

Go to https://github.com/NissesSenap/ocp4GoodToHave/tree/master/grafana_easy and follow the instructions.

All this is built on https://github.com/integr8ly/grafana-operator/
If you choose to follow the official instructions the important part is how you set the Thanos datasource password.

You can find it here:

openshift_prometheus_basic_auth_pass=$GRAFANA_DATASOURCE_PASSWORD

export GRAFANA_DATASOURCE_PASSWORD=$(oc get secret grafana-datasources -n openshift-monitoring -o jsonpath='{.data.prometheus\.yaml}' | base64 --decode | jq .datasources[0].basicAuthPassword | sed 's/"//g' )
echo $GRAFANA_DATASOURCE_PASSWORD

**NOTE MAC USERS** look at the, I know that sed is different on Linux and Mac and I don't know if this is one of the cases. Don't have a Mac so I can't test it ^^

And a example of the data source here:
https://github.com/NissesSenap/ocp4GoodToHave/blob/master/grafana_easy/grafana/templates/grafana-thanos-datasource.yaml

## OpenLiberty stuff

This part you know much better than I do.

Send up your favorite OpenLiberty app and scrape it using prometheus.
Use the grafana example dashboard that you have in the repo.

To add the dashboard to the grafana you need to ether login as admin in grafana.
If you followed my installer I didn't set any default password.

You can find the password here:

```oc get secret grafana-admin-credentials -n grafana -o yaml``` and look under data.

If you rather want to use graphs as pipelines you can do that as well by using the GrafanaDashboard CR.
Check out https://github.com/integr8ly/grafana-operator/tree/master/deploy/examples/dashboards

**Comment by Yushan-Lin** [comment]
Hi @NissesSenap, I have tried out the dashboard and can reproduce your problem. I think your proposed solution makes the most sense in this case. You can replace https://github.com/OpenLiberty/open-liberty-operator/blob/3bc64dbf2f265001d89c20d7e96a9a014c10eccb/deploy/dashboards/metrics/RHOCP4.3-GrafanaOperator3.0.2-Grafana5.2/open-liberty-grafana-mpMetrics2.x.yml#L3253 with `"regex": "/base_cpu_processCpuLoad_percent{.*pod=\"(.*)\",prometheus=.*,service=.*/"`, which would filter out the prometheus label. I haven't tested with larger clusters, but we don't really have a story to support this scenario.

**Comment by Yushan-Lin** [comment]
FYI @NissesSenap We're updating the dashboards #207 .

**Comment by NissesSenap** [comment]
Thanks so much for your help @Yushan-Lin.
I verified just now and it works like a charm.
