### ISSUE TITLE
Broken link to Observability with Open Liberty causes 404 page not found

### ISSUE THREAD

**Issue by pdfruth** [OpenLiberty/open-liberty-operator#208]
## Bug Report

This page;
https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/readme.adoc

Contains a link to "Observability with Open Liberty"
The link currently points to;
https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.3.adoc

That page does not exist.  Thus, a 404 page not found error.

The link should point to;
https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.4.adoc

**Comment by leochr** [comment]
@ellen-lau It seems the link was broken when the instructions and file name were modified to support newer version of OCP. Could you please address the broken link? Thank you.
