### ISSUE TITLE
Validation required for unsupported parameters

### ISSUE THREAD

**Issue by kishkulk** [OpenLiberty/open-liberty-operator#223]
### What did you do?
I tried the bellow sample yaml file

apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: my-liberty-app-1
spec:
  replicas: 3
  applicationImage: 'open-liberty:1.0'
  name:` "test"

In the above yaml 'name' is not a supported parameter of OpenLibertyApplication but still the CR is created.

### What did you expect to see?

I expected an error telling args parameter is not supported. 

### What did you see instead?

CR created successfully

**Comment by leochr** [comment]
@kishkulk The OpenLibertyApplication controller/reconciler wouldn't get details about the unsupported parameters, they'll be stripped away, so it has no way to do any validation. This is true with any resource (i.e. Deployment - if you add an unsupported field, it just gets removed).

**Comment by leochr** [comment]
Operator wouldn't get details about the invalid fields (in this case `.spec.name`). It's stripped away by Kuberetes. It can only validate valid CR fields.
