### ISSUE TITLE
Address: `Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

### ISSUE THREAD

**Issue by edburns** [OpenLiberty/open-liberty-operator#234]
### Is your feature request related to a generic (non-Open Liberty) problem?

No.

If so, please open an issue with the [upstream Operator](https://github.com/application-stacks/runtime-component-operator/issues), which gets pulled into this Operator.

### Is your feature request related to a problem?

A clear and concise description of what the problem is. Example: "I have an issue when (...)"

Using Azure Kubernetes service, when I run `kubectl apply -f https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.1/openliberty-app-crd.yaml` I see:

```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/openlibertyapplications.openliberty.io unchanged
customresourcedefinition.apiextensions.k8s.io/openlibertytraces.openliberty.io unchanged
customresourcedefinition.apiextensions.k8s.io/openlibertydumps.openliberty.io unchanged
```
Version info:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-13T17:14:18Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

### Describe the solution you'd like

I would I think it is as simple as changing `apiVersion: apiextensions.k8s.io/v1beta1` to `apiVersion: apiextensions.k8s.io/v1` but of course there is the little matter of testing and certifying.

**Comment by leochr** [comment]
@edburns We are planning to update the k8s beta versions (v1beta1) to stable version (v1) as we move Open Liberty Operator from beta to 1.0.0.

**Comment by leochr** [comment]
This is resolved with the release of Open Liberty Operator 1.2.0+, which uses `apiextensions.k8s.io/v1` for the CustomResourceDefinition
