### ISSUE TITLE
Convert tests to run on new framework

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#238]
Existing tests are not compatible with operator-sdk 1.x. Convert existing tests to one of the new testing framework (kuttl, scorecard, env-test).

**Comment by idlewis** [comment]
The kappnav, service binding, and certmanager tests are not going to be converted.

**Comment by idlewis** [comment]
The branch kuttl-tests is still WIP, but contains most converted tests, the exceptions being
knative - this test is waiting for the update to the new operator sdk version
dump&trace - these tests are still beind worked on

**Comment by yongja79** [comment]
Basic dump and trace tests added
Work on making the tests run under Scorecard will need to wait till #237 is completed
