### ISSUE TITLE
OLO operator supports K8s 1.22 in a useable release as soon as possible

### ISSUE THREAD

**Issue by anneqm** [OpenLiberty/open-liberty-operator#248]
## Feature Request
Open Liberty Operator with Kubernets 1.22 dependency that removes the 11 deprecated APIs is needed for CP4Apps 5.1, WebSphere Hybrid Edition and other areas of our portfolio so they can run on OCP 4.9. This is a breaking change and ideally would be available as an OLO release within 30 days of OCP GA. 

### Is your feature request related to a generic (non-Open Liberty) problem?
CP4Apps 5.1  needs the new OLO release with dependency on kubernets 1.22, which removes 11 deprecated APIs. 

If so, please open an issue with the [upstream Operator](https://github.com/application-stacks/runtime-component-operator/issues), which gets pulled into this Operator.

### Is your feature request related to a problem?

A clear and concise description of what the problem is. Example: "I have an issue when (...)"

- OLO will not run on OCP 4.9 ( which GAs Oct 18, 2021) without this feature. 

### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

- Complete conversion to K8s 1.22 and release in a usable format (1.0.0) preferably in mid-November.

**Comment by leochr** [comment]
Delivered. Closing
