### ISSUE TITLE
Resources changed in namespace are not reconciled 

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/open-liberty-operator#253]
## Bug Report

I am consuming cert-manager certificates in my liberty application when I updated resources in the namespace and they are not refreshed from liberty operator. I deleted route and the operator not reconciled with the route. I have pet store app CRs on multiple namespaces and some how the route is not getting reconciled on one of the namespace 

### What did you do?

A clear and concise description of the steps you took (or insert a code snippet).

1. Install OpenLiberty operator
2. Create sample app CRs in two different namespaces.
3. Delete route in one of the namespace and the route is not reconciled.

### What did you expect to see?

A clear and concise description of what you expected to happen (or insert a code snippet). If possible, add 

A route has to be reconciled when it is deleted in the namespace.

### What did you see instead?

I did not see reconciliation happening when we delete route resource. 
### Environment

* Kubernetes version information:

* OpenShift version information (if applicable):

```
oc version
Client Version: 4.6.16
Server Version: 4.6.42
```

* Appsody CLI version (if applicable):

* Appsody Stack (if applicable):

**Comment by leochr** [comment]
Closing. Please reopen if the issue persists.
