### ISSUE TITLE
Add Field for Route Pathway in OLA

### ISSUE THREAD

**Issue by tylerstanczak** [OpenLiberty/open-liberty-operator#290]
### Is your feature request related to a problem?

When I expose an application via the _spec.expose_ boolean, it defaults to the liberty root. I have to manually adjust the route to point it to my application context root.

### Describe the solution you'd like

I would like an additional field in the OpenLibertyApplication that allows me to set a custom pathway in the Route, without having to manually edit the Route after it is created. Maybe something such as _spec.expose.pathway_

**Comment by leochr** [comment]
@tylerstanczak There is already `route.path` field that you can set it to. Please try with that. Thanks.
