### ISSUE TITLE
insecureEdgeTerminationPolicy: Redirect is not set on the Route

### ISSUE THREAD

**Issue by deleeuwblue** [OpenLiberty/open-liberty-operator#297]
### What did you do?

I deployed an application with the following CR:

cat <<EOF | oc apply -f -
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: ibmdeveloper-liberty-app
spec:
  applicationImage: de.icr.io/ibmdeveloper/wlp:1
  service:
    type: ClusterIP
    certificateSecretRef: ibmdevelopercert
    port: 9443
  expose: true
  route:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
    host: www.deleeuw.me.uk
EOF

### What did you expect to see?

I expected a passthrough route which allows insecure traffic.

### What did you see instead?

In the OCP U for the RouteI, the field "Insecure Traffic" in the section "TLS Settings" is blank.  Therefore the application is not available via HTTP, only HTTPS (which works fine).

The YAML for the generated OpenLibery CR looks like this (includes insecureEdgeTerminationPolicy):

apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"openliberty.io/v1beta1","kind":"OpenLibertyApplication","metadata":{"annotations":{},"name":"ibmdeveloper-liberty-app","namespace":"ibm-developer"},"spec":{"applicationImage":"de.icr.io/ibmdeveloper/wlp:1","expose":true,"route":{"host":"www.deleeuw.me.uk","insecureEdgeTerminationPolicy":"Redirect","termination":"passthrough"},"service":{"certificateSecretRef":"ibmdevelopercert","port":9443,"type":"ClusterIP"}}}
  selfLink: >-
    /apis/openliberty.io/v1beta1/namespaces/ibm-developer/openlibertyapplications/ibmdeveloper-liberty-app
  resourceVersion: '4528363'
  name: ibmdeveloper-liberty-app
  uid: 362564e4-65e3-43fe-b7d0-a022dc8ea794
  creationTimestamp: '2021-11-24T11:34:47Z'
  generation: 2
  managedFields:
    - apiVersion: openliberty.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          .: {}
          'f:applicationImage': {}
          'f:expose': {}
          'f:route':
            .: {}
            'f:host': {}
            'f:insecureEdgeTerminationPolicy': {}
            'f:termination': {}
          'f:service':
            .: {}
            'f:certificateSecretRef': {}
            'f:port': {}
            'f:type': {}
      manager: oc
      operation: Update
      time: '2021-11-24T11:34:47Z'
    - apiVersion: openliberty.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:applicationName': {}
          'f:pullPolicy': {}
          'f:resourceConstraints': {}
        'f:status':
          .: {}
          'f:conditions': {}
          'f:imageReference': {}
      manager: open-liberty-operator
      operation: Update
      time: '2021-11-25T18:26:42Z'
  namespace: ibm-developer
spec:
  applicationImage: 'de.icr.io/ibmdeveloper/wlp:1'
  applicationName: ibmdeveloper-liberty-app
  expose: true
  pullPolicy: IfNotPresent
  resourceConstraints: {}
  route:
    host: www.deleeuw.me.uk
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  service:
    certificateSecretRef: ibmdevelopercert
    port: 9443
    type: ClusterIP
status:
  conditions:
    - lastTransitionTime: '2021-11-24T11:34:47Z'
      lastUpdateTime: '2021-11-25T18:26:42Z'
      status: 'True'
      type: DependenciesSatisfied
    - lastTransitionTime: '2021-11-24T11:34:47Z'
      lastUpdateTime: '2021-11-25T18:26:42Z'
      status: 'True'
      type: Reconciled
  imageReference: 'de.icr.io/ibmdeveloper/wlp:1'

The YAML for the generated Route looks like this (does not include insecureEdgeTerminationPolicy):

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  selfLink: >-
    /apis/route.openshift.io/v1/namespaces/ibm-developer/routes/ibmdeveloper-liberty-app
  resourceVersion: '3770770'
  name: ibmdeveloper-liberty-app
  uid: a871d30c-3719-47e9-aa6e-f0c31002ffa8
  creationTimestamp: '2021-11-25T08:54:17Z'
  managedFields:
    - manager: open-liberty-operator
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2021-11-25T08:54:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"362564e4-65e3-43fe-b7d0-a022dc8ea794"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:host': {}
          'f:port':
            .: {}
            'f:targetPort': {}
          'f:tls':
            .: {}
            'f:termination': {}
          'f:to':
            'f:kind': {}
            'f:name': {}
            'f:weight': {}
          'f:wildcardPolicy': {}
    - manager: openshift-router
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2021-11-25T08:54:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:ingress': {}
  namespace: ibm-developer
  ownerReferences:
    - apiVersion: openliberty.io/v1beta1
      kind: OpenLibertyApplication
      name: ibmdeveloper-liberty-app
      uid: 362564e4-65e3-43fe-b7d0-a022dc8ea794
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: ibmdeveloper-liberty-app
    app.kubernetes.io/managed-by: open-liberty-operator
    app.kubernetes.io/name: ibmdeveloper-liberty-app
    app.kubernetes.io/part-of: ibmdeveloper-liberty-app
spec:
  host: www.deleeuw.me.uk
  to:
    kind: Service
    name: ibmdeveloper-liberty-app
    weight: 100
  port:
    targetPort: 9443-tcp
  tls:
    termination: passthrough
  wildcardPolicy: None
status:
  ingress:
    - host: www.deleeuw.me.uk
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2021-11-25T08:54:17Z'
      wildcardPolicy: None
      routerCanonicalHostname: >-
        sample-9aacca1089941763ef3f71d03b1d3aa5-0000.eu-de.containers.appdomain.cloud

### Environment

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d5ed12c", GitCommit:"d5ed12c2580a64bf7125514c06435b4144a77e31", GitTreeState:"clean", BuildDate:"2021-09-17T23:43:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

* OpenShift version information (if applicable):

Client Version: openshift-clients-4.2.2-201910250432
Server Version: 4.6.47
Kubernetes Version: v1.19.0+d5ed12c

* Appsody CLI version (if applicable):

* Appsody Stack (if applicable):

### Additional context

I installed the OpenLiberty Operator from the OperatorHub, it shows version 0.7.0

The OpenShift cluster is deployed as a service from IBM Cloud

**Comment by mtamboli** [comment]
I also saw exact same problem where `redirect` does not work if you have `passthru` but works as expected for `reencrypt`. I saw this on OLO 0.8.0

**Comment by leochr** [comment]
Open Liberty Operator v0.8.1 is now released with the fix for this issue. Release information is documented [here](https://github.com/OpenLiberty/open-liberty-operator/releases/tag/v0.8.1).

fyi @deleeuwblue @mtamboli
