### ISSUE TITLE
No 0.8.0 installation guide for kubectl

### ISSUE THREAD

**Issue by dfateyev** [OpenLiberty/open-liberty-operator#302]
### What did you do?

There are no installation instructions for 0.8.0 release, using "kubectl" and pure Kubernetes cluster.
I have checked [the updated release guide](https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1beta2.adoc) and official [Readme](https://github.com/OpenLiberty/open-liberty-operator/blob/main/README.md).

There is no specific version directory in "deploy", as it was for previous versions.
https://github.com/OpenLiberty/open-liberty-operator/tree/v0.8.0/deploy/releases
I believe deploying from "daily" is unsuitable and not that we should get there.

### What did you expect to see?

Please provide updated docs or instruction, and "deploy/releases/0.8.0" bundle (if applicable)

**Comment by leochr** [comment]
@dfateyev We've added the install instructions here: https://github.com/OpenLiberty/open-liberty-operator/tree/main/deploy/releases/0.8.0#installation

Install options with OLM and kustomize (with kubectl) are documented. We are currently working on the documentation for kubectl only (similar to 0.7.1). Let you know when that's available.

**Comment by leochr** [comment]
@dfateyev Install instructions with kubectl is now documented at https://github.com/OpenLiberty/open-liberty-operator/tree/main/deploy/releases/0.8.0/kubectl

**Comment by dfateyev** [comment]
@leochr in general, works fine — but the links to yaml files in the article above are incorrect.
Need to fix the links, to get it working out if box.

**Comment by leochr** [comment]
@dfateyev Thanks for bringing this to our attention. I believe some files moved, resulting in URLs not working. 
@halim-lee could you please update the links (_kubectl_ folder is missing)? Thanks
