### ISSUE TITLE
Openliberty 0.8.0 not available in OperatorHub(.io)

### ISSUE THREAD

**Issue by LDL-GH** [OpenLiberty/open-liberty-operator#305]
### What did you do?

Updating the OpenLibertyOperator  to 0.8.0 does not seem to be possible using the operatorhub available in OpenShift.
It's the same experience when looking up the operator on operatorhub.io:
https://operatorhub.io/operator/open-liberty

### What did you expect to see?

The OpenLibertyOperator should be available to be updated using the means available in openshift.

### Environment

* OpenShift version information (if applicable):

openshift 4.7.31

**Comment by leochr** [comment]
@LDL-GH We are in the process of making Open Liberty Operator 0.8.0 available to OpenShift's OperatorHub as well as community OperatorHub. I'll update when they are available there. Thanks.

**Comment by leochr** [comment]
@LDL-GH Open Liberty Operator 0.8.0 is now available from OperatorHub in OpenShift

**Comment by leochr** [comment]
Closing: 0.8.0 is now available in OperatorHub in OpenShift (Certified Catalog).
