### ISSUE TITLE
Image Pull Error

### ISSUE THREAD

**Issue by pain29-coder** [OpenLiberty/open-liberty-operator#351]
## Type of question

Are you asking about best practices, how to configure the Open Liberty operator, or about general context and help around the operator?

I have two questions regarding operator install. I am trying to install operator in OpenShift through Operator hub via Web console. Filtered for open liberty certified operator , selected the beta2 channel and selected all namespaces install mode. 

a. The install plan fails and when I checked the pod logs under openshift-marketspace namespace found the following error. How to fix this?

Error:

Failed to pull image "registry.connect.redhat.com/ibm/open-liberty-operator-controller@sha256:18f188e48725c785557c8edea46f69c464d6f81ab47860a3bb0ec978c20a26db": rpc error: code = Unknown desc = Source image rejected: Running image docker://registry.connect.redhat.com/ibm/open-liberty-operator-controller@sha256:18f188e48725c785557c8edea46f69c464d6f81ab47860a3bb0ec978c20a26db is rejected by policy.

2. During installation when I select install mode as "All Namespace" via web console, it doesn't allow me to select under what namespace the operator would be installed. The drop down is greyed out and the default selection is "openshift-operator" name space. Is it not possible to select our own name space when using install mode as "All_Namespace".

### What did you do?

A clear and concise description of the steps you took (or insert a code snippet). If possible, add `OpenLibertyApplication` CR.

### What did you expect to see?

A clear and concise description of what you expected to happen (or insert a code snippet).

### What did you see instead? Under which circumstances?

A clear and concise description of what you expected to happen (or insert a code snippet).

### Environment

* Kubernetes version information:

* OpenShift version information (if applicable):

* Appsody CLI version (if applicable):

* Appsody Stack (if applicable):

**Comment by pain29-coder** [comment]
I got the answer for the first one. The registry was blocked, so we opened it. Could you assist with the question 2?

**Comment by leochr** [comment]
@pain29-coder Regarding question 2, yes, OpenShift selects `openshift-operator` for All namespace install mode. It's not something that Open Liberty Operator has control over.

**Comment by pain29-coder** [comment]
Thank you for the quick response.
