### ISSUE TITLE
Route path is not removed when path line is deleted

### ISSUE THREAD

**Issue by danielguinan1** [OpenLiberty/open-liberty-operator#363]
### What did you do?

when deleting this part of the route in the OpenLibertyApplication yaml
```
route:
    path: /daytrader
```
the route does not change to remove the path unless I delete the route.

### What did you expect to see?

I expected to see the route path removed.

### What did you see instead?

The route path stayed the same as if the path was not deleted.

### Environment

* OpenShift version information (if applicable):

4.10.3

### Possible solution

operator could check if path is not present (nil) and then set Route path to /

### Additional context

Very minor issue, but if I specify the path in the OLA yaml then edit it removing the path line it does not update the route unless it is deleted.  If I change it to path: / or path: "" it removes the path from the route.  By default the yaml has expose: true but no path set.

- RCO
   - [x] Fixed
   - [x] Added tests
- OLO
   - [x] Fixed
   - [x] Added tests
- WLO
   - [x] Fixed
   - [x] Added tests

**Comment by leochr** [comment]
Same as the following issue on RCO's backlog: https://github.com/application-stacks/runtime-component-operator/issues/299

**Comment by leochr** [comment]
@danielguinan1 This should now be fixed for all 3 Operators

**Comment by leochr** [comment]
@idlewis please add the tests for OLO and WLO when you get a chance. Thank you

**Comment by leochr** [comment]
Closing as completed
