### ISSUE TITLE
Synchronize OLO with WLO

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#376]
- [x] Operator-sdk and dependency updates for OLO
- [x] Functionalities from WLO - i.e. Semeru Compiler
- [x] Manifests, API metadata
- [x] Tests

**Comment by halim-lee** [comment]
https://github.com/OpenLiberty/open-liberty-operator/pull/393

**Comment by halim-lee** [comment]
Kind Tests: https://github.com/OpenLiberty/open-liberty-operator/pull/394
