### ISSUE TITLE
Open Liberty Operator 0.3.0 (Go-based)

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#41]
Create Go-based operator for Open Liberty. It'll be based on the [Appsody operator](https://github.com/appsody/appsody-operator) v0.3.0

**Comment by leochr** [comment]
Delivered. Closing.

**Comment by arthurdm** [comment]
Re-opening to add design link & comments / feedback.

**Comment by arthurdm** [comment]
Design doc: https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/operator-design.md

**Comment by arthurdm** [comment]
Feedback from the design:

- ensure that Jane (developer) has a seamless transition from working with an Application Stack that was using the Appsody Operator to now working with an Application Stack using the Open Liberty Operator.
- open issues for related open source and umbrella projects that need to be updated to support using the Open Liberty Operator (ensure they include new regression testing).

**Comment by leochr** [comment]
Delivered.
