### ISSUE TITLE
Validate kubectl install artifacts for OLO and RCO 1.2.0

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#413]
- Install the operator using kubectl install option for all supported install modes (OwnNamespace, AllNamespaces and SingleNamespace). 
- Run the kuttl e2e tests and validate that they pass
- **Clean up between each install mode** (delete relevant namespaces, kubernetes resources and CRDs - `kubectl delete` instead can be used with all the install commands)

**Comment by leochr** [comment]
@idlewis kubectl install artifacts for 1.2.0 are now available:
- OLO: https://github.com/OpenLiberty/open-liberty-operator/tree/main/internal/deploy/1.2.0/kubectl
- RCO: https://github.com/application-stacks/runtime-component-operator/tree/main/internal/deploy/1.2.0/kubectl

Please validate it by running the kuttl tests in all install modes using the instructions provided in the folder. I believe that the first command to apply CRDs should be updated to `kubectl create` instead of `kubectl apply`, please confirm. Thank you

**Comment by idlewis** [comment]
@leochr testing for rco complete, all passed.
PR to tweak the docs is application-stacks/runtime-component-operator#533

**Comment by idlewis** [comment]
testing for olo complete, everything passed.
OpenLiberty/open-liberty-operator#421 was opened for a few minor tweaks
