### ISSUE TITLE
Release Open Liberty operator v0.3.0

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#44]
Open Liberty operator v0.3.0 will be based on/include Appsody Operator v0.3.0
- [x] Release in GitHub
- [x] Update OperatorHub.io 
- [x] Certify it (embedded OpenShift OperatorHub)

**Comment by arthurdm** [comment]
I updated the description to add certification

**Comment by leochr** [comment]
Submitted the necessary changes.
