### ISSUE TITLE
Document that resources operator creates and manages shouldn't be edited manually

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#45]
OpenShift provides a UI to edit certain resources (e.g. Health Checks), but it shouldn't be used to alter the resources that the operator creates and manages. Because it'll get out of sync and those manual changes will be lost with the subsequent reconciliation by the operator. Add documentation to capture this.

**Comment by arturdzm** [comment]
Operator will be watching sub-resources, users will not be able to modify operator controlled values
