### ISSUE TITLE
Remove deprecated keys in Kustomize deploy scripts

### ISSUE THREAD

**Issue by kabicin** [OpenLiberty/open-liberty-operator#460]
When using an overlay such as `kubectl apply --server-side -k overlays/watch-another-namespace` the Kustomize scripts encounter the following deprecation warnings for the `bases` and `patchesStrategicMerge` keys (tested on Kustomize 4.5.5)
```
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```
Update the Kustomize scripts in the `internal` folder to use non-deprecated keys for subsequent releases.

Fixed in:

- [x] RCO
- [x] OLO
- [x] WLO

**Comment by idlewis** [comment]
All patches merged
