### ISSUE TITLE
Support disabling auto mounting of the service account token

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#462]
Provide an easy way to disable auto mounting of the service account token. There is an workaround that requires pre-creating a service account with that option and configuring the CR to use it.

Kube docs show how to configure the service account to opt out of automounting the token:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting

Add this as a config option to the CRD with a default of 'true' i.e. default to mounting the service acount token

- [x] RCO
- [x] OLO
- [x] WLO
- [x] Tests
- [x] Doc updates

**Comment by leochr** [comment]
@idlewis I came across these references to the depreacted`.spec.ServiceAccountName` in the controller, which should also consider the new field. Similar references are also in OLO and WLO
https://github.com/application-stacks/runtime-component-operator/blob/e24b121659e542d34ae1db360441d2eb67d65fcb/controllers/runtimecomponent_controller.go#L208

**Comment by leochr** [comment]
@idlewis Thanks for the PRs to remove references to the deprecated field in the controllers. Please evaluate if additional test cases are needed, which potentially would have caught this before. Thank you

**Comment by idlewis** [comment]
I think this issue is now complete. WLO docs aren't published yet, but changes are all ready

**Comment by leochr** [comment]
Closing as completed
