### ISSUE TITLE
Build multi-arch image for Open Liberty operator

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#48]
Right now the operator images we have are only for x86. We need to build a Travis pipeline that builds also powerLinux and zLinux and pushes them (with a fat manifest) into Docker Hub.

Original issue: https://github.ibm.com/WASCloudPrivate/roadmap-cloudpaks/issues/546

**Comment by arthurdm** [comment]
We want to get this done for 1Q20, but doesn't need to be in the 4Q19 delivery, so removing from the 0.2.0 epic.

**Comment by edavidj** [comment]
Multi-arch manifest lists are now pushed from GHE
