### ISSUE TITLE
Support OCP 4.15

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#518]
Add support for OpenShift 4.15

Tentative release date: ~March 2024~ February 27, 2024

**Comment by halim-lee** [comment]
Version updates:
- Go
- Go project
- operator-sdk
- Kubernetes APIs
- Dependencies

**Comment by leochr** [comment]
Closing as completed. Claimed support for OCP 4.15 with existing Operator 1.3.1
