### ISSUE TITLE
Add observedGeneration field to CR status

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#535]
To improve ability to check if spec matches reconciled version
metadata.generation should be copied into status.observedGeneration once all resources are updated / created.

This can be looked up to ensure that the updates to CR are actually processed. 

Users could get the current observedGeneration value before doing an update and then do an `oc wait` for the generation to be greater than the current value.

- [ ] Doc updates
- [ ] Tests

**Comment by kabicin** [comment]
Added observed generation tests here https://github.ibm.com/websphere/operators/pull/101.

**Comment by leochr** [comment]
@kabicin Thanks for the above PRs. Merged them.

Please add the RCO doc change to OLO as well. Also, raise a doc issue with ID to update WLO. Thanks
