### ISSUE TITLE
Remove the usage of deprecated features

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#553]
Remove the usage of the following deprecated APIs/features :
- CoreDNS wildcard queries for the `cluster.local` domain -  deprecated since at least 4.13
- `ImageContentSourcePolicy` (ICSP) objects - deprecated since at least 4.13
- Kubernetes topology label `failure-domain.beta.kubernetes.io/zone`  and `failure-domain.beta.kubernetes.io/region` - deprecated since at least 4.13
- `operators.openshift.io/infrastructure-features` annotations - deprecated in 4.14 - see this for replacement - have both till 4.12 goes out of support
- [x] RCO
- [x] OLO
- [x] WLO
- [x] Common Operators
- [ ] Docs
- [ ] Tests

**Comment by leochr** [comment]
@halim-lee Should this be moved to Review/QA (instead of Closing)?

**Comment by halim-lee** [comment]
@leochr Sorry, moved a wrong one over to closed. Got confused with removing the operator-build-scripts repo for WSA.
