### ISSUE TITLE
Increase the memory limit of the Operator

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#564]
On a cluster where the Liberty Operator is installed in AllNamespaces mode (cluster-wide), the many instances of custom resources (CRs) across many namespaces could result in high memory usage and in some cases could run out of memory and crash the container. As a result, the CR instances won't be reconciled by the Operator. This was observed with 512MB memory limit. Hence, consider increasing the limit to 1024MB. The Operator will start off with 128 MB (memory request) and then ONLY use the additional memory if required.

- [x] Delivered to OLO
- [x] Delivered to RCO
- [x] Delivered to WLO

**Comment by kabicin** [comment]
Updated the current internal folder and manifests (no backport) 
- RCO: https://github.com/application-stacks/runtime-component-operator/pull/625
- WLO: https://github.com/WASdev/websphere-liberty-operator/pull/635
- OLO: https://github.com/OpenLiberty/open-liberty-operator/pull/571

**Comment by leochr** [comment]
Closing as completed. Thank you
