### ISSUE TITLE
Run acceptance tests (FVT) with OCP 4.16 and k8s 1.29

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#576]
Use the latest version of WLO and 
- [x] run acceptance tests with OCP 4.16 on all supported platforms (X, P and Z)
- [x] run acceptance tests on non-OCP with Kubernetes 1.29

**Comment by halim-lee** [comment]
All kuttl tests passed on `kindest/node:v1.29.4`: [test result](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/ab2d03e7-55ae-420d-863b-c74c6818d65c/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south)

**Comment by leochr** [comment]
@halim-lee It could be awhile before Fyre officially adds 4.16 support. Let's use the OCP pre-release capability in our OnePipeline to run the WLO FVT on XYZ with 4.16 by setting `pre-release` to true. I already updated `pre-release-*` flags accordingly to use 4.16. Thank you

**Comment by halim-lee** [comment]
@leochr The tests passed on OCP 4.16 X except for `routes` test.
```
        Name: routes
        State: fail

        Errors:
                resource Route:operator-test/route: .spec.host: value mismatch, expected: route-operator-test.foo.bar.com != actual: route-operator-test.apps.was-416.cp.fyre.ibm.com
```

This test fails on 4.15 locally. For AllNamespaces mode, the `defaultHostname` needs to be set for ConfigMap in `openshift-operators` namespace.

**Comment by halim-lee** [comment]
Both cases are tested and passed

**Comment by leochr** [comment]
Thank you @halim-lee. Cosing as completed
