### ISSUE TITLE
Document resource requirements

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#577]
Document the memory/cpu request and limits of the Operator

- [x] Completed for OLO
- [x] Completed for RCO

WLO already documents here: https://www.ibm.com/docs/en/was-liberty/base?topic=requirements-sizing

**Comment by kabicin** [comment]
Doc update PRs
OLO: https://github.com/OpenLiberty/open-liberty-operator/pull/585
RCO: https://github.com/application-stacks/runtime-component-operator/pull/634
