### ISSUE TITLE
Reevaluate go replace for certain packages

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#581]
The `go.mod` includes some replace instructions for certain packages. Evaluate whether they are still needed. If needed, can the versions be moved up?

```
replace (
	//To resolve license issue - https://github.com/operator-framework/operator-registry/issues/190
	github.com/otiai10/copy => github.com/otiai10/copy v1.0.2
	github.com/otiai10/mint => github.com/otiai10/mint v1.3.0
	github.com/prometheus/client_golang => github.com/prometheus/client_golang v1.11.1
	golang.org/x/text => golang.org/x/text v0.4.0
)

replace github.com/docker/docker => github.com/moby/moby v0.7.3-0.20190826074503-38ab9da00309 // Required by Helm
```

- [ ] Completed for OLO
- [ ] Completed for RCO
- [ ] Completed for WLO

**Comment by kabicin** [comment]
ready for review
RCO: https://github.com/application-stacks/runtime-component-operator/pull/639
WLO: https://github.com/WASdev/websphere-liberty-operator/pull/654
OLO: https://github.com/OpenLiberty/open-liberty-operator/pull/591

**Comment by leochr** [comment]
Delivered. Closing
