### ISSUE TITLE
Fix up the example in the CSV alm-examples

### ISSUE THREAD

**Issue by kaczyns** [OpenLiberty/open-liberty-operator#6]
The `alm-examples` text shows up in the Open Shift console when you want to create a new instance of our CRD.  This is what's currently there:
```json
    alm-examples: |-
      [{
       "apiVersion": "openliberty.io/v1alpha1",
       "kind": "OpenLiberty",
       "metadata": {
          "name": "my-app-deployment"
       },
       "spec": {
          "image": {
            "tag": "1.0.0",
            "repository": "myrepo/my-app"
          },
          "mancenter": {
            "image": {
              "tag": "3.11.3"
            }
          },
          "hazelcast": {
            "licenseKeySecretName": "hz-license-key-secret"
          },
          "serviceAccount": {
            "create": false,
            "name": "hazelcast"
          }
       }
      }]
```
We should put a more appropriate example there, preferably with some comments explaining why someone might want to change some of the fields.  I think that taking most of the defaults is fine, but we should include a short blurb about how to replace the container with your own, or how to define the HTTP ports, etc.

**Comment by mezarin** [comment]
Closing this issue. It was fixed under PR: #12.
