### ISSUE TITLE
Set environment variables for logging console 

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#62]
Set the following environment variables by default. We should allow users to override these using the `env` parameter. 

- name: `WLP_LOGGING_CONSOLE_LOGLEVEL`
value: info
- name: `WLP_LOGGING_CONSOLE_SOURCE`
value: message,trace,accessLog,ffdc
- name: `WLP_LOGGING_CONSOLE_FORMAT`
value: json

FYI @donbourne

**Comment by leochr** [comment]
@edavidj Please set some additional env variables related to logging. Also, remove the `logs.consoleFormat` parameter altogether as users can override using the `env` parameter.

**Comment by edavidj** [comment]
> @edavidj Please set some additional env variables related to logging. Also, remove the `logs.consoleFormat` parameter altogether as users can override using the `env` parameter.

Sounds good, can add those defaults.  If we're not going to include them as parameters explicitly, should I document those variables and their defaults somewhere?

**Comment by leochr** [comment]
Yes, please document the default environment variables we set along with their values and how users can override (using the `env` parameter) in this section:
https://github.com/OpenLiberty/open-liberty-operator/blob/master/docs/user-guide.md#environment-variables
