### ISSUE TITLE
Add shortname to CRD

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/open-liberty-operator#63]
It's error prone to type oc get `openlibertyapplication`, so we should look into adding a shortname for our CRD.

The proposal is for `olapp` and `olapps` (singular / plural) shortnames.

**Comment by leochr** [comment]
Similarly for the trace and dump operations, we'll have shortnames.

OpenLibertyTrace: `oltrace` and `oltraces`
OpenLibertyDump: `oldump` and `oldumps`

**Comment by leochr** [comment]
Delivered
