### ISSUE TITLE
Run kind-e2e tests on Kubernetes 1.30

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#635]
Run kind-e2e tests on Kubernetes 1.30

**Comment by leochr** [comment]
@halim-lee As part of the OCP 4.17 support, we’ll also need to claim support for the equivalent Kubernetes 1.30. Could you please look into running the kind-e2e tests with 1.30? 

I am hoping that we can claim OCP 4.17 and k8s 1.30 support using the already-released 1.4.0 - that's assuming no changes are needed in go.mod / go.sum and there are no breaking changes that'll require Operator changes. 

I already kicked off builds on OCP 4.17 on all platforms, so they can be skipped in your build using `SKIP_OCP_E2E_TEST`.

I also set `release-acceptance-test` to use the 1.4.0 GA images instead of building new images. Not sure if kind-e2e considers this property though. If not, it would be fine to build new images using the main branch if that'll be faster as we haven't made significant changes since the 1.4.0 release.

**Comment by halim-lee** [comment]
kind-e2e supports `release-acceptance-test` as well.
WLO 1.4.0 release passed with Kubernetes v1.30.4: https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/c459ee26-541d-49f5-a10a-392127647b4b/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south
RCO and OLO builds are running.

**Comment by halim-lee** [comment]
RCO 1.4.0 release also passed: https://cloud.ibm.com/devops/pipelines/tekton/729b3aea-0a81-4b4d-bd42-7e5811980010/runs/582ae8fb-5aa6-4010-b3d8-28d8f5cdc256/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south

**Comment by leochr** [comment]
@halim-lee Thank you. Closing as completed
