### ISSUE TITLE
Document Operator configration options for OLO and RCO

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#669]
Document the field configurable using the Operator ConfigMap (similar to WLO's https://www.ibm.com/docs/en/was-liberty/base?topic=operator-configmap).

Add this to OLO's doc, but reference from RCO's doc page (mention that the name of the ConfigMap is different for RCO.

- [x] Completed for OLO
- [x] Completed for RCO

**Comment by halim-lee** [comment]
Closing as completed
