### ISSUE TITLE
Support OpenID Connect / Social Login

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/open-liberty-operator#86]
We need a way to make it easy to configure an Open Liberty deployment to take advantage of OpenID Connect / Social Login capabilities.

Some of this work will be at the container level via server configuration (with environment variables place holders), but the more complex part of this work will be at the Operator level to fetch the relevant data and populate the snippets (via env vars).   Also need to consider doing file mounts, if the data is sensitive (e.g. credentials).  

This probably needs to work with a set of OpenID Connect Providers (Keycloak, Open Liberty OP, etc).

**Comment by arthurdm** [comment]
CC @jtmulvey and @chunlongliang-ibm

**Comment by arturdzm** [comment]
Just a pointer for discovery connection information of the OpenID Provider for the clients

https://YOUR_DOMAIN/.well-known/openid-configuration
This is part of OpenID specification 
https://auth0.com/docs/protocols/oidc/openid-connect-discovery

**Comment by brutif** [comment]
related to https://github.com/OpenLiberty/open-liberty/issues/9821

**Comment by arthurdm** [comment]
Some notes I took from our call:

## Stage 1:
-  create a `socialLogin` snippet in both WL and OL (replace the current OIDC snippet)
- these snippets should use the standard Liberty variable name (see [here](https://openliberty.io/docs/ref/config/serverConfiguration.html) for more info), which means they can either be overridden by env variables (in a dev case), or by injecting XML `<variable>` snippets (production case)
- update the OpenLibertyApplication CRD to have a field where the user supplies the name of the secret that contains the OIDC provider info (items `id` and `secret` I think)
- the operator will create the corresponding `<variable>` snippet with those values and inject that into the config overrides.

## Stage 2
- user can set a boolean to enable the auto-discovery and injection of OpenShift SSO credentials 
- the operator needs to find those values ((still `id` and `secret`?) and inject the `<variable>` snippet.
