### ISSUE TITLE
There is no baseline to use when merging changes made after running `operator-sdk`

### ISSUE THREAD

**Issue by kaczyns** [OpenLiberty/open-liberty-operator#9]
The current contents of many objects (CRD, CSV, etc) are not the same as those generated by `operator-sdk`.  After upgrading to the latest version of `operator-sdk` it is difficult to know what has changed, so that it can be merged into this git repository.  We should create a baseline folder in this git repository which contains the output of `operator-sdk`, as well version information, so that when we switch to a new version of `operator-sdk` we know what needs to be merged in (if anything), in addition to updating the baseline.

**Comment by kaczyns** [comment]
Further to what is written above, this is the file system structure I'm proposing for the files in this git repository:
```
open-liberty-operator
├── baseline
│   ├── <output of "operator-sdk new --type=helm ...>
│   └── Readme.md <explain that this is only used for rebasing >
├── build
│   └── Dockerfile
├── deploy
│   ├── crds
│   │   ├── charts_v1alpha1_openliberty_crd.yaml
│   │   └── charts_v1alpha1_ibmopenliberty_cr.yaml
│   ├── operator.yaml
│   ├── role_binding.yaml
│   ├── role.yaml
│   └── service_account.yaml
├── helm-charts
│   └── <whatever gets generated here by operator_sdk>
├── olm
│   ├── open-liberty-0.0.1.clusterserviceversion.yaml
│   ├── open-liberty-crd.yaml
│   └── open-liberty-package.yaml
├── scripts
│   └── < stuff we use to help package / test >
├── Readme.md <install instructions for standalone vs olm>
└── watches.yaml
```
Some explanation:
1) The baseline directory is used to store the output of `operator-sdk new --type=helm ...` without any changes.  The development team will use this when upgrading either `operator-sdk` or the helm chart, to detect what is changed, and what needs to get rolled into the `deploy` or `olm` directories (or other places potentially).  The `Readme.md` in this directory should explain this, and should list the versions of `operator-sdk` that was used, and the version of the helm chart used.  The readme should be updated when we switch versions.
2) The build directory is generated by `operator-sdk`
3) The deploy directory holds the files that would be used by someone deploying the operator without using OLM.  Instructions for using these files should be in the root `Readme.md`
4) The helm-charts directory is generated by `operator-sdk`
5) The olm directory contains the files that are submitted to https://github.com/operator-framework/community-operators
6) The scripts directory contains scripts we've made to help our build process along.  For example, it should contain a script that runs `operator-sdk scorecard` after moving around files into a temporary directory in the places that `scorecard` expects them to be.

**Comment by arthurdm** [comment]
That sounds very reasonable to me @kaczyns    +1

The only thing we need to watch out for is that our current OL helm chart is resides in this repository is a bit different than the one available from the github.com/ibm/charts repo - we plan on synchronizing the two at the near future.
