### ISSUE TITLE
Add automated tests for new features

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#92]
Ensure the new features have automated tests.
- [x] Service binding
- [x] Imagestream
- [x] Certificate management integration
- [x] Social login
- [x] kAppNav integration

Add anything else not covered by the automated tests.

We should have unit tests, basic tests and advanced scenario tests. Please open issues as necessary and link to this Epic.

**Comment by edavidj** [comment]
These tests have all been added, the minimal functionality that still requires work (namely auto-reg in SSO e2e tests) doesn't warrant keeping the epic open.
