### ISSUE TITLE
Consider not having a messages.log by default

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty-operator#94]
Since the OL Operator is writing JSON logs to stdout (console), it may not be necessary to also have a messages.log file (since users can see the same logs from the container log output).

In order for the console output to contain everything normally in the messages.log you would need the following environment variables to be set:

```
WLP_LOGGING_CONSOLE_FORMAT=json
WLP_LOGGING_CONSOLE_LOGLEVEL=info
WLP_LOGGING_CONSOLE_SOURCE=message,trace,accessLog,ffdc,audit
```

messages.log can be disabled as follows:

```
WLP_LOGGING_MESSAGE_FORMAT=json
WLP_LOGGING_MESSAGE_SOURCE=
```

**Comment by edavidj** [comment]
Given #95 , would we maybe want to target something like the below without trace and with message.log disabled? 
```
WLP_LOGGING_CONSOLE_FORMAT=json
WLP_LOGGING_CONSOLE_LOGLEVEL=info
WLP_LOGGING_CONSOLE_SOURCE=message,accessLog,ffdc,audit

WLP_LOGGING_MESSAGE_FORMAT=json
WLP_LOGGING_MESSAGE_SOURCE=
```

**Comment by donbourne** [comment]
@edavidj , that's what I was thinking too... just opened them as two separate issues to avoid conflating the two problems.

**Comment by edavidj** [comment]
awesome, just wanted to make sure I understood correctly. 

@arthurdm / @leochr would this conflict with any existing functionality / target use cases that you're aware of?

**Comment by arthurdm** [comment]
sounds good to me.   I guess as long as we first check that we're not conflicting with the container's env vars, or the CR YAML env vars.

**Comment by donbourne** [comment]
Hey guys, had a discussion about this related to support.  Support teams rely on the messages.log and would likely not be able to get at logs if they are only going to the EFK stack.  While logs for current containers could be accessed with kubectl logs, logs for containers that have stopped still need to be accessible.

**Comment by edavidj** [comment]
Thanks for the update. See #96 for updated list of variables set to turn tracing off but keep messages.log
