### ISSUE TITLE
discussion on what docker image snippets need to look like for operator to support socialLogin

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty-operator#98]
This is to avoid cluttering up #86.  It's not intended to put any code here.

**Comment by brutif** [comment]
Don't take this as design gospel, because it will probably mutate as we discuss it.

In Liberty, an instance configured for all the social media providers would look like this:
```
<featureManager> would have added
       <feature>appSecurity-3.0</feature>
        <feature>socialLogin-1.0</feature>
```

And the ssl config needs to have "trustDefaultCerts=true". (we can probalby just default that)
```
<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaulKeyStore" trustDefaultCerts="true" /> 
```

And finally each social login provider (>=1) gets a client id and secret specified 
```
<githubLogin   clientid="blah"          clientSecret="blah" />
    <facebookLogin clientid="blah"          clientSecret="blah"/>    
    <linkedinLogin  clientid="blah"          clientSecret="blah"/> 
    <twitterLogin clientid="blah"          clientSecret="blah"/>
    <googleLogin   clientid="blah"          clientSecret="blah"/>
```

**Comment by brutif** [comment]
Discussing today 
- we'll just do the 5 preconfigured providers first, try to make 3/11.
- certificate issue may be moot once the liberty operator can add the cluster root ca to the liberty pods. 
- generic config can follow the way rhsso works (fairly detailed yaml), CL to draft something up in next day or so.

**Comment by leochr** [comment]
@brutif Had further discussions on this. To avoid manipulating the container too much and to have the social login flags on the image side to have real value, it'll be good to also have the actual snippets (with Liberty variables) for the 5 providers on the image side. The operator would inject the values for those Liberty variables.

**Comment by brutif** [comment]
Chunlong's thinking we should do the more general (and complex) ones first. Here's a table.  There's two types, oidcLogin and Oauth2Login.  If either is used, there are just a few params that are not optional, but most are optional, so it's hard to put a one-size-fits-all substitution snippet into the image. 

attribute name                                      | Optional if used | Default Value    | XML example reference |  notes 
 --------------------------------------------------- | -------------- | ---------------- | --------------------- | ---------------------
socialLogin.enabled                                  | yes            |   false          |                       |
xml attributes:                                      |                |                  |                       |
socialLogin.oidcLogin.id                             | no             |                  |                       |
socialLogin.oidcLogin.secretRef                      | no             |                  |                       |
socialLogin.oidcLogin.discoveryEndpoint              | no             |                  |                       |
socialLogin.oidcLogin.groupNameAttribute             | yes            |                  |                       |
socialLogin.oidcLogin.userNameAttribute              | yes            |                  |                       |
socialLogin.oidcLogin.displayName                    | yes            |                  |                       |
socialLogin.oidcLogin.userInfoEndpointEnabled        | yes            |                  |                       |
socialLogin.oidcLogin.mapToUserRegistry              | yes            |                  |                       |
socialLogin.oidcLogin.realmNameAttribute             | yes            |                  |                       |
socialLogin.oidcLogin.scope                          | yes            |                  |                       |
socialLogin.oidcLogin.tokenEndpointAuthMethod        | yes            |                  |                       |
socialLogin.oidcLogin.redirectToRPHostAndPort        | no             |                  |                       |
xml attributes:                                       |                |                  |                       |
socialLogin.oauth2Login.id                           | no             |                  |                       |
socialLogin.oauth2Login.secretRef                    | no             |                  |                       |
socialLogin.oauth2Login.scope                        | yes            |                  |                       |
socialLogin.oauth2Login.tokenEndpoint                | no             |                  |                       |
socialLogin.oauth2Login.authorizationEndpoint        | no             |                  |                       |
socialLogin.oauth2Login.userApi                      | no             |                  |                       |
socialLogin.oauth2Login.userNameAttribute            | yes            |                  |                       |
socialLogin.oauth2Login.groupNameAttribute           | yes            |                  |                       |
socialLogin.oauth2Login.mapToUserRegistry            | yes            |                  |                       |
socialLogin.oauth2Login.realmName                    | yes            |                  |                       |
socialLogin.oauth2Login.redirectToRPHostAndPort      | no             |                  |                       |
socialLogin.oauth2Login.tokenEndpointAuthMethod      | yes            |                  |                       |
socialLogin.oauth2Login.accessTokenHeaderName        | yes            |                  |                       |
socialLogin.oauth2Login.accessTokenRequired          | yes            |                  |                       |
socialLogin.oauth2Login.userApiType                  | yes            |                  |                       | enum of basic,kube,introspect

**Comment by brutif** [comment]
Here's the general problem we need to figure out.  Given this xml:
```
<!--- (1)              (2)                 (3)  -->
<oidcLogin mandatoryAttrib="foo"  optionalAttrib="bar" ... />
```
1 The entire element is only present if an oidcLogin is defined.
2 If the element is present, some mandatory attributes will always be present, so can be templated.
3 Optional attributes may or may not be present and have no fixed default value so cannot be templated. 
4 All of this requires https which the operator didn't offer last time I looked.
We need an approach to conditionally form and insert the xml elements as shown above.

**Comment by brutif** [comment]
Trial balloon here: https://github.com/OpenLiberty/ci.docker/pull/145
operator writes some stuff to bootstrap.properties (or appends to existing one)
entries in bs.props drive some includes from /config/optional_includes
more entries in bs.props add mandatory and optional params.
sample bs.props:
```
# the following mandatory fields would all be added by the operator
# 1) Add the include file if the particular form of social login is to be used. 
#    If not used, one must add the name of a nonexistent file
# (due to liberty not using server.xml variables in the include location attribute)

social-oidc-include=social-oidc-include.xml
social-oauth-include=no-op.xml

# 2) Add the required attributes that were supplied to the operator, or operator read from secret.

oidcLogin.clientId=theclientid
oidcLogin.clientSecret=thesecret
oidcLogin.redirectToRPHostAndPort=http://localhost:12345
oidcLogin.discoveryEndpoint=https://sso-default.apps.corners.os.fyre.ibm.com/auth/realms/master/.well-known/openid-configuration

# 3) Add any overrides of optional attributes supplied to the operator.
oidcLogin.scope=openid profile email phone picture mobile birthday friends 
```

**Comment by brutif** [comment]
Here's another way we could do it without using bootstrap.properties or the new /config/optional-includes folder.  Operator could:  
- pass a env var "social_login_providers" which would contain a string listing all the providers the operator user has selected be used, i.e. "google oidc linkedin facebook twitter". 
- configure.sh reads that and copies the selected provider snippets in like any other snippets.   - - Those snippets expect required and optional params, those can be set like "normal" liberty variables, passed through env, server.xml snippet,  bootstrap.properties, or any combination of those.  That would make it easier for security to test, as we can fully test the docker image's ability to consume all the parameters independent of the operator.

**Comment by leochr** [comment]
@brutif Thank you for the prototype. I like the approach of specifying optional attributes using Liberty variables with defaults. Also, the names of the variables to differentiate between oidcLogin and oauth2Login is ideal. 

configure.sh is invoked at image build time, so operator wouldn’t be able to pass the provider information to it. We can instead have an argument at the image level (e.g. SOCIAL_LOGIN_PROVIDERS=google, github, oidc). Based on the values, we can add the server config snippets to corresponding providers. This way, we can also do away with the optional includes.

**Comment by brutif** [comment]
Here are the current attributes, draft image changes are at https://github.com/OpenLiberty/ci.docker/pull/145

PHASE 1  (try for 3/11 ?)
secretRef secret contains clientId and clientSecret

 attribute name                              | Reqd | Default   |
 ------------------------------------------- | -----|----------|
sso.enabled                                  |   n  |   false   |
oidc attribs:                                            |      |           |
sso.oidcLogin.id                             |   y  |           |
sso.oidcLogin.secretRef                      |   y  |           |
sso.oidcLogin.discoveryEndpoint              |   y  |           |
sso.oidcLogin.redirectToRPHostAndPort        | y     |           |
sso.oidcLogin.groupNameAttribute             |      |           |
sso.oidcLogin.userNameAttribute              |      |           |
sso.oidcLogin.displayName                    |      |           |
sso.oidcLogin.userInfoEndpointEnabled        |      |           |
sso.oidcLogin.mapToUserRegistry              |      |           |
sso.oidcLogin.realmNameAttribute             |      |           |
sso.oidcLogin.scope                          |      |           |
sso.oidcLogin.tokenEndpointAuthMethod        |      |           |
oauth attribs:                                             |      |           |
sso.oauth2Login.id                           |  y   |           |
sso.oauth2Login.secretRef                    |  y   |           |
sso.oauth2Login.redirectToRPHostAndPort      |  y   |           |
sso.oauth2Login.scope                        |      |           |
sso.oauth2Login.tokenEndpoint                |      |           |
sso.oauth2Login.authorizationEndpoint        |      |           |
sso.oauth2Login.userApi                      |      |           |
sso.oauth2Login.userNameAttribute            |      |           |
sso.oauth2Login.groupNameAttribute           |      |           |
sso.oauth2Login.mapToUserRegistry            |      |           |
sso.oauth2Login.tokenEndpointAuthMethod      |      |           |
sso.oauth2Login.accessTokenHeaderName        |      |           |
sso.oauth2Login.accessTokenRequired          |      |           |
sso.oauth2Login.userApiType                  |      |           |


PHASE 2 (all are required except sso.githubLogin.hostName)

sso.githubLogin.secretRef
sso.githubLogin.redirectToRPHostAndPort
sso.githubLogin.mapToUserRegistry
sso.githubLogin.hostName

sso.facebookLogin.secretRef
sso.facebookLogin.redirecToRPHostAndPort
sso.facebLogin.mapToUserRegistry

sso.linkedinLogin.secretRef
sso.linkedinLogin.redirectToRPHostAndPort
sso.linkedinLogin.mapToUserRegistry

sso.twitterLogin.secretRef
sso.twitterLogin.redirectToRPHostAndPort
sso.twitterLogin.mapToUserRegistry

sso.googleLogin.secretRef
sso.gogleLogin.redirectToRPHostAndPort
sso.googleLogin.mapToUserRegistry

**Comment by leochr** [comment]
@arthurdm fyi, the configurable attributes for different providers are listed above.

**Comment by arthurdm** [comment]
Thanks @leochr.    What's the difference between phase 1 and phase 2 attributes?   The ones from phase 2 look a lot cleaner / easier to refactor into a common CR element.

**Comment by brutif** [comment]
@arthur @leochr this is stale, current design is at https://github.com/OpenLiberty/ci.docker/pull/145

**Comment by brutif** [comment]
closing, superseded by OpenLiberty/ci.docker#145
